### ISSUE TITLE
implement a retry mechanism

### ISSUE THREAD

**Issue by aklira** [fledge-iot/fledge-south-iec104#2]
Current behaviour: the plugin initiates a connection to the remote server on the south service start call. But if the connection is lot, the plugin won't retry to connect to the remote server.

Expected behaviour: the plugin should permanently test that the connection is alive and initiate retries on a fixed period (value should be specified in the configuration with default value = 30s) if connection is lost.

**Comment by Slayce** [comment]
This issue has been resolved :
The current behavior is now that when the connection is lost, the plugin sets itself in a state of waiting for new connection. It doesn't have to initiate retries since it uses the event handler to check if there is a new connection, it is thus passive and triggered by the connection request.
